name: street_food
description: 길거리 간식(푸드트럭) 하이브리드 지도 MVP
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  kakao_map_plugin: ^0.4.0
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  uuid: ^4.5.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
